improvements

diff --git a/apps/aarch64-linux/install b/apps/aarch64-linux/install
--- a/apps/aarch64-linux/install
+++ b/apps/aarch64-linux/install
@@ -11,18 +11,28 @@ check_installer() {
 }
 
 cleanup() {
-  rm -rf nix-config-nixos-config.zip nix-config-nixos-config
+  rm -rf nixos-config-main.zip nixos-config-main nixos-config
 }
 
 download_config() {
-  curl -LJ0 https://github.com/iverberk/nix-config/archive/refs/heads/nixos-config.zip -o nix-config-nixos-config.zip
-  unzip nix-config-nixos-config.zip
-  cd nix-config-nixos-config
+  curl -LJ0 https://github.com/dustinlyons/nixos-config/archive/main.zip -o nixos-config-main.zip
+  unzip nixos-config-main.zip
+  mv nixos-config-main/templates/starter nixos-config
+  cd nixos-config
+}
+
+run_apply() {
+  ./apps/x86_64-linux/apply
+  if [ ! -f /tmp/username.txt ]; then
+    echo -e "\e[1;31mError: /tmp/username.txt does not exist.\e[0m"
+    exit 1
+  fi
+  export USERNAME=$(cat /tmp/username.txt)
 }
 
 run_disko() {
   sudo nix run --extra-experimental-features nix-command --extra-experimental-features flakes \
-    github:nix-community/disko -- --mode zap_create_mount ./nixos/disk-config.nix
+    github:nix-community/disko -- --mode zap_create_mount ./modules/nixos/disk-config.nix
 }
 
 setup_files() {
@@ -62,6 +72,7 @@ prompt_reboot() {
 cleanup
 check_installer
 download_config
+run_apply
 run_disko
 setup_files
 install_nixos
